# Generated by Django 3.1.6 on 2021-03-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_auto_20210308_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='school_notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_subject', models.CharField(max_length=200)),
                ('motice_details', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthDate', models.DateField()),
                ('address', models.TextField()),
                ('phoneNumber', models.IntegerField()),
                ('positon', models.CharField(max_length=200)),
                ('teacherimage', models.ImageField(upload_to='teacher_pic')),
                ('className', models.ManyToManyField(to='student.StudentClass')),
            ],
        ),
    ]
