# Generated by Django 3.1.6 on 2021-02-07 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school_notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_subject', models.CharField(max_length=200)),
                ('motice_details', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthDate', models.DateField()),
                ('address', models.TextField()),
                ('phoneNumber', models.IntegerField()),
                ('positon', models.CharField(max_length=200)),
                ('teacherimage', models.ImageField(upload_to='teacher_pic')),
                ('className', models.ManyToManyField(to='adminSite.StudentClass')),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('registration_no', models.CharField(default='#202169745', max_length=100)),
                ('birthDate', models.DateField()),
                ('address', models.TextField()),
                ('phoneNumber', models.IntegerField()),
                ('studentimage', models.ImageField(upload_to='student_pic')),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminSite.studentclass')),
            ],
        ),
    ]
