# Generated by Django 3.1.6 on 2021-02-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='registration_no',
            field=models.CharField(default='#2021360783', max_length=100),
        ),
    ]
