# Generated by Django 3.1.6 on 2021-02-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSite', '0003_auto_20210207_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='registration_no',
            field=models.CharField(default='#2021596912', max_length=100),
        ),
    ]
