# Generated by Django 3.1.6 on 2021-03-08 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianInfo',
            fields=[
                ('registration_no', models.IntegerField(primary_key=True, serialize=False)),
                ('father_name', models.CharField(max_length=100)),
                ('father_phone_no', models.CharField(blank=True, max_length=11, null=True)),
                ('father_occupation', models.CharField(blank=True, choices=[('Agriculture', 'Agriculture'), ('Banker', 'Banker'), ('Business', 'Business'), ('Doctor', 'Doctor'), ('Farmer', 'Farmer'), ('Fisherman', 'Fisherman'), ('Public Service', 'Public Service'), ('Private Service', 'Private Service'), ('Shopkeeper', 'Shopkeeper'), ('Driver', 'Driver'), ('Worker', 'Worker'), ('N/A', 'N/A')], max_length=45, null=True)),
                ('father_yearly_income', models.IntegerField(blank=True, null=True)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_phone_no', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_ocupation', models.CharField(blank=True, choices=[('Agriculture', 'Agriculture'), ('Banker', 'Banker'), ('Business', 'Business'), ('Doctor', 'Doctor'), ('Farmer', 'Farmer'), ('Fisherman', 'Fisherman'), ('Public Service', 'Public Service'), ('Private Service', 'Private Service'), ('Shopkeeper', 'Shopkeeper'), ('Driver', 'Driver'), ('Worker', 'Worker'), ('House wife', 'House wife'), ('N/A', 'N/A')], max_length=45, null=True)),
                ('mother_yearly_income', models.IntegerField(blank=True, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=110, null=True)),
                ('guadian_phone_no', models.CharField(blank=True, max_length=11, null=True)),
                ('relationship_with_student', models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Uncle', 'Uncle'), ('Aunt', 'Aunt')], max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousAcademicInfo',
            fields=[
                ('registration_no', models.IntegerField(primary_key=True, serialize=False)),
                ('institute_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_exam', models.CharField(blank=True, max_length=100, null=True)),
                ('group', models.CharField(blank=True, max_length=45, null=True)),
                ('gpa', models.CharField(blank=True, max_length=10, null=True)),
                ('board_roll', models.IntegerField(blank=True, null=True)),
                ('passing_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('registration_no', models.CharField(default='2021511325', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('roll', models.IntegerField(blank=True, null=True)),
                ('birthDate', models.DateField()),
                ('details_address', models.TextField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('upazilla', models.CharField(blank=True, max_length=255, null=True)),
                ('village', models.TextField(blank=True, max_length=255, null=True)),
                ('phoneNumber', models.IntegerField()),
                ('studentimage', models.ImageField(upload_to='student_pic')),
                ('blod_groop', models.CharField(blank=True, choices=[('a+', 'A+'), ('o+', 'O+'), ('b+', 'B+'), ('ab+', 'AB+'), ('a-', 'A-'), ('o-', 'O-'), ('b-', 'B-'), ('ab-', 'AB+')], max_length=5, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=110)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birth_certificate_no', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Hinduism', 'Hinduism'), ('Buddhism', 'Buddhism'), ('Christianity', 'Christianity'), ('Others', 'Others')], max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('Bangladeshi', 'Bangladeshi'), ('Others', 'Others')], max_length=255, null=True)),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.studentclass')),
            ],
        ),
    ]
