# Generated by Django 3.1.6 on 2021-03-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='registration_no',
            field=models.CharField(default='2021885814', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
